spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5433/birthday_db
    username: birthday
    password: birthday123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  error:
    whitelabel:
      enabled: false
